version: "3.8"

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      target: development
      args:
        HERMES_FE_PORT: ${HERMES_FE_PORT} # Pass the environment variable as a build argument
    ports:
      - ${HERMES_FE_PORT}:${HERMES_FE_PORT}
    environment:
      - HERMES_FE_PORT=${HERMES_FE_PORT}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    container_name: backend
    build:
      context: ./backend
      args:
        HERMES_BE_PORT: ${HERMES_BE_PORT} # Pass the environment variable as a build argument
    environment:
      - HERMES_BE_PORT=${HERMES_BE_PORT}
    ports:
      - ${HERMES_BE_PORT}:${HERMES_BE_PORT}
    volumes:
      - ./backend:/app
      - ./frontend/dist:/app/frontend/dist
    networks:
      - app-network
    environment:
      - PYTHONUNBUFFERED=1

networks:
  app-network:
    driver: bridge
