version: "3.8"
services:
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - backend

  backend:
    container_name: backend
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
