version: "3.8"

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      target: development
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./frontend/dist:/app/frontend/dist
    networks:
      - app-network
    environment:
      - PYTHONUNBUFFERED=1
  
networks:
  app-network:
    driver: bridge
