name: Deploy

on:
  push:
    tags:
      - 'deploy-site'  # This triggers the workflow only when a tag named 'deploy-site' is pushed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Server
      run: |
        if [[ "${GITHUB_REF}" == "refs/tags/deploy-site" ]]; then
          BRANCH=$(git rev-parse --abbrev-ref HEAD)
          if [[ "$BRANCH" == "dev" ]]; then
            echo "Deploying dev environment"
            ssh -o StrictHostKeyChecking=no xbnrxout@xavrema.com "bash /home/xbnrxout/deploy_hermes.sh dev"
          elif [[ "$BRANCH" == "main" ]]; then
            echo "Deploying main environment"
            ssh -o StrictHostKeyChecking=no xbnrxout@xavrema.com "bash /home/xbnrxout/deploy_hermes.sh main"
          else
            echo "No deployment configured for this branch"
          fi
        fi
